name: Download Pages with Inliner

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install inliner
      run: npm install -g inliner
    
    - name: Download and inline pages
      run: |
        mkdir -p downloaded_pages_inliner
        inliner -m --videos https://time.ir > downloaded_pages_inliner/time.html
        echo "✅ Saved"
        sleep 2
    
    
    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        add: 'downloaded_pages_inliner/'
        message: 'Download web pages with inliner'
        default_author: github_actions
        token: ${{ secrets.GITHUB_TOKEN }}
